### ISSUE TITLE
[Resource 86] Yoruba transcriptions in the root resource directory are wrong.

### ISSUE THREAD

**Issue by agutkin** [danpovey/openslr#5]
The following index files for Yoruba datasets are wrong:

  http://www.openslr.org/resources/86/line_index_female.tsv
  http://www.openslr.org/resources/86/line_index_male.tsv

The above files have South-American Spanish lines instead of Yoruba transcriptions. Is it possible to replace these with the line_index.tsv files from the corresponding zip files?

  line_index_female.tsv   <--  yo_ng_female.zip/line_index.tsv
  line_index_male.tsv <-- yo_ng_male.zip/line_index.tsv

My apologies, have only noticed this bug now.

**Comment by danpovey** [comment]
@jtrmal any chance you could look at this?

**Comment by jtrmal** [comment]
yes.
Alex, would it be possible to open the PR against openslr-org/openslr?
y.

**Comment by danpovey** [comment]
its an issue not a PR, not sure if can be done as PR because need change of
content (zip file) not metadata

**Comment by jtrmal** [comment]
ah, sorry, I got confused somehow...
y.

**Comment by jtrmal** [comment]
replaced
y.

**Comment by jtrmal** [comment]
Alex, please confirm...
y.

**Comment by agutkin** [comment]
Excellent! Correct Jan. Thank you!
